/**GET DATA**/
curl --location --request GET 'https://fxuduknsd5.execute-api.us-east-1.amazonaws.com/latest'
curl --location --request GET 'https://fxuduknsd5.execute-api.us-east-1.amazonaws.com/latest/test'


/**POST DATA**/
curl --location --request POST 'https://fxuduknsd5.execute-api.us-east-1.amazonaws.com/latest/add' --header 'Content-Type: application/json' --data-raw '{ "name": "Rasikh" }'
curl --location --request PUT 'https://fxuduknsd5.execute-api.us-east-1.amazonaws.com/latest/edit' --header 'Content-Type: application/json' --data-raw '{ "name": "Rasikh" }'

/**PUT DATA**/
